name: build
run-name: Build and Test Project
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gcc -v
      - run: gcc -c -o revlib.o revlib.c
      - run: gcc reverse.c revlib.o -o reverse
      - run: echo 2345 | ./reverse  # runs the program
      - run: make test
